service: plapo
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x

functions:
  #  getActiveRooms:
  #    handler: controller.get_active_rooms
  #    events:
  #      - http:
  #          path: plapo
  #          method: get
  - CreateRoom:
      handler: controller.create_new_room
      events:
        - http:
            path: plapo/createRoom
            method: get



plugins:
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-python-requirements
custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true

resources:
  Resources:
    Tables:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: plapo
        AttributeDefinitions:
          - AttributeName: record_id
            AttributeType: S
          - AttributeName: room_id
            AttributeType: S
          - AttributeName: member_id
            AttributeType: S
        KeySchema:
          - AttributeName: record_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: room_id-member_id-index
            KeySchema:
              - AttributeName: room_id
                KeyType: HASH
              - AttributeName: member_id
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1

