service: plapo
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x

functions:
  #  getActiveRooms:
  #    handler: controller.get_active_rooms
  #    events:
  #      - http:
  #          path: plapo
  #          method: get
  - CreateRoom:
      handler: controller.create_new_room
      events:
        - http:
            path: plapo/createRoom
            method: get



plugins:
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-python-requirements
custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true

resources:
  Resources:
    Tables:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: plapo
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
